### ISSUE TITLE
Failed to setup on Docker HA

### ISSUE THREAD

**Issue by davemcmath** [tonyroberts/hawundasmart#40]
Can't seem to get it to connect properly .....

Installed custom components folder. 

http sniffed username and password.

Setup says success then shows...

![image](https://github.com/user-attachments/assets/5f074eea-e37e-4c5e-b01e-6a7580cc03cc)

tried increasing timeouts to 30, no difference.

iPhone app works fine to communicate with hub.

Any help would be really appreciated.

  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.66.98:80 ssl:default [Connect call failed ('192.168.66.98', 80)]
2024-11-19 19:11:15.691 WARNING (MainThread) [custom_components.wundasmart] Failed to fetch state information from Wundasmart (will retry): result={'state': False, 'code': 500, 'message': 'HTTP client error'}
2024-11-19 19:11:18.760 WARNING (MainThread) [custom_components.wundasmart.pywundasmart] Error getting syncvalues.cgi
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.66.98', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/wundasmart/pywundasmart.py", line 136, in get_devices
    async with httpsession.get(wunda_url,
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    , proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.66.98:80 ssl:default [Connect call failed ('192.168.66.98', 80)]
2024-11-19 19:11:18.765 WARNING (MainThread) [custom_components.wundasmart] Failed to fetch state information from Wundasmart: result={'state': False, 'code': 500, 'message': 'HTTP client error'}

**Comment by davemcmath** [comment]
thanks for that nudge and troubleshooting command.

It was a strange routing issue because im using MAC_vlan with docker and it wasn't using the default route. 

Added a static route to get out my normal ethernet port and works perfectly. Now to setup the 80 entities! its now just found.

Thanks again! I'll close the issue now if I can.

**Comment by davemcmath** [comment]
Closing
